version: '3.7'

services:
  etod:
    image: mka142/etogd
    volumes:
      - ./credentials.json:/etogd/credentials.json
      - ./token.json:/etogd/token.json
      #- /some/machine/path/data:/etogd/sources/DATA
    environment:
      #- SOURCES_TO_BACKUP=DATA_ARCHIVE:/etogd/sources/DATA_ARCHIVE
      - GDRIVE_PARENT_FOLDER=
      - SCHEDULE_TIME=
    env_file: 
      - ./.env